homeassistant:
  # Name of the location where Home Assistant is running
  name: !secret ha_name
  # Location required to calculate the time the sun rises and sets
  #latitude: 52.3857576
  latitude: !secret ha_latitude
  #longitude: 20.8932268
  longitude: !secret ha_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 100
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Warsaw
  # Customization file
  customize: !include customize.yaml


logger:
  default: info
  logs:
      homeassistant.components.sensor.test_consumption_1d_2 : debug
      homeassistant.components.sensor.test_consumption_1d: debug
  #    homeassistant.components.binary_sensor.test: debug
  #    homeassistant.components.sensor.test: debug

# Show links to resources in log and frontend
#introduction:

                
# Enables configuration UI
config:

http:
  # Uncomment this to add a password (recommended!)
  # api_password: PASSWORD
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  # base_url: example.duckdns.org:8123

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

frontend:
    themes:
        green:
            #https://github.com/brianjking/homeassistant-config/blob/master/configuration.yaml#L167
            primary-color: "#1DE9B6" # Primary (most of the UI)
            primary-background-color: "#303030" # Primary background colour (dialogs, e.t.c)
            secondary-background-color: "#303030" # Secondary background colour (main UI background)
            paper-card-background-color: "#424242" # Card background colour
            paper-item-icon-color: "#1DE9B6" # Icon colour
            primary-text-color: "#FFFFFF" # Primary text colour
            secondary-text-color: "rgba(255, 255, 255, 0.7)" # Secondary text colour
            disabled-text-color: "rgba(255, 255, 255, 0.5)" # Disabled text colour
            divider-color: "rgba(255, 255, 255, 0.12)" # Divider colour
            paper-card-header-color: "#FFFFFF" # Card header text colourV    
            # Nav Menu #
            paper-listbox-background-color: "#424242" # Listbox background colour
            paper-listbox-color: "#FFFFFF" # Listbox text colour
            paper-grey-200: "#616161" # Listbox selected item background colour
            # Switches #
            paper-toggle-button-checked-ink-color: "#1DE9B6"
            paper-toggle-button-checked-button-color: "#1DE9B6"
            paper-toggle-button-checked-bar-color: "#1DE9B6"
            # Sliders #
            paper-slider-knob-color: "#1DE9B6"
            paper-slider-knob-start-color: "#1DE9B6"
            paper-slider-pin-color: "#1DE9B6"
            paper-slider-active-color: "#1DE9B6"
            paper-slider-secondary-color: "#33F2D8"
        dark_orange:
            primary-color: "#ff9800"
            light-primary-color: "#ffc947"
            dark-primary-color: "#c66900"
            text-primary-color: "#ffffff"
            primary-background-color: "#37464f"
            sidebar-text_-_background: "#62717b"
            paper-card-background-color: "#263137"
            paper-card-header-color: "var(--text-primary-color)"
            secondary-background-color: "var(--primary-background-color)"
            primary-text-color: "var(--text-primary-color)"
            secondary-text-color: "var(--primary-color)"
            paper-listbox-background-color: "var(--sidebar-text_-_background)"
            paper-toggle-button-checked-ink-color: "var(--dark-primary-color)"
            paper-toggle-button-checked-button-color: "var(--dark-primary-color)"
            paper-toggle-button-checked-bar-color: "var(--dark-primary-color)"
            paper-slider-knob-color: "var(--primary-color)"
            paper-slider-knob-start-color: "var(--primary-color)"
            paper-slider-pin-color: "var(--primary-color)"
            paper-slider-active-color: "var(--primary-color)"
            paper-slider-secondary-color: "var(--light-primary-color)"
            paper-slider-container-color: "var(--sidebar-text_-_background)"
            paper-progress-secondary-color: "var(--sidebar-text_-_background)"
            paper-item-selected_-_background-color: "var(--primary-color)"
            paper-item-icon_-_color: "var(--text-primary-color)"
            paper-item-icon-color: "var(--sidebar-text_-_background)"
            paper-item-icon-active-color: "var(--primary-color)"
            paper-grey-50: "var(--sidebar-text_-_background)"
            paper-grey-200: "var(--primary-background-color)"
            label-badge-background-color: "var(--sidebar-text_-_background)"
            label-badge-text-color: "var(--text-primary-color)"
            label-badge-red: "var(--primary-color)"
            label-badge-blue: "var(--light-primary-color)"
            label-badge-green: "var(--dark-primary-color)"
            label-badge-yellow: "var(--text-primary-color)"
            label-badge-grey: "var(--paper-grey-500)"
            table-row-background-color: "var(--paper-card-background-color)"
            table-row-alternative-background-color: "var(--sidebar-text_-_background)"
        dark_red:
            # Main colors that can be changed
            dark-primary-color: "#c66900"
            disabled-text-color: "#545454"
            divider-color: "rgba(255, 255, 255, 0.12)"
            light-primary-color: "#e06c6c"
            paper-card-background-color: "#1d1d1d"
            paper-grey-200: "#191919"
            paper-item-icon-color: "#d3d3d3"
            paper-listbox-background-color: "#202020"
            primary-background-color: "#303030"
            primary-color: "#d32f2f"
            primary-text-color: "#cfcfcf"
            secondary-background-color: "#131313"
            sidebar-text_-_background: "#62717b"
            # Colors based on variables, see above
            paper-card-header-color: "var(--paper-item-icon-color)"
            paper-item-icon-active-color: "var(--primary-color)"
            paper-item-icon_-_color: "var(--primary-text-color)"
            paper-listbox-color: "var(--primary-text-color)"
            paper-grey-50: "var(--primary-text-color)"
            paper-slider-active-color: "var(--primary-color)"
            paper-slider-knob-color: "var(--primary-color)"
            paper-slider-knob-start-color: "var(--primary-color)"
            paper-slider-pin-color: "var(--primary-color)"
            paper-slider-secondary-color: "var(--light-primary-color)"
            paper-toggle-button-checked-ink-color: "var(--dark-primary-color)"
            paper-toggle-button-checked-button-color: "var(--primary-color)"
            paper-toggle-button-checked-bar-color: "var(--light-primary-color)"
            paper-toggle-button-unchecked-bar-color: "var(--primary-text-color)"
            secondary-text-color: "var(--primary-color)"
            table-row-background-color: "var(--paper-card-background-color)"
            table-row-alternative-background-color: "var(--sidebar-text_-_background)"
        dark_cyan:
            # Main colors that can be changed
            primary-color: "#00bcd4"
            disabled-text-color: "#545454"
            divider-color: "rgba(255, 255, 255, 0.12)"
            paper-card-background-color: "#4e4e4e"
            paper-grey-200: "#191919"
            paper-item-icon-color: "#d3d3d3"
            paper-listbox-background-color: "#202020"
            paper-listbox-color: "#FFFFFF"
            primary-background-color: "#303030"
            primary-text-color: "#cfcfcf"      
            secondary-background-color: "#2b2b2b"
            secondary-text-color: "#04a7bc" 
            # Colors based on variables, see above
            label-badge-background-color: "var(--secondary-background-color)"
            label-badge-text-color: "var(--text-primary-color)"
            paper-card-header-color: "#var(--paper-item-icon-color)"
            paper-grey-50: "var(--primary-text-color)"
            paper-item-icon-active-color: "var(--primary-color)"
            paper-item-icon_-_color: "var(--primary-text-color)"
            paper-slider-active-color: "var(--primary-color)"
            paper-slider-knob-color: "var(--primary-color)"
            paper-slider-knob-start-color: "var(--primary-color)"
            paper-slider-pin-color: "var(--primary-color)"
            paper-slider-secondary-color: "var(--light-primary-color)"
            paper-toggle-button-checked-ink-color: "var(--dark-primary-color)"
            paper-toggle-button-checked-button-color: "var(--primary-color)"
            paper-toggle-button-checked-bar-color: "var(--light-primary-color)"
            paper-toggle-button-unchecked-bar-color: "var(--primary-text-color)"



# Track the sun
sun:

mqtt:
    broker: localhost
    discovery: true
    discovery_prefix: homeassistant
    #username: your_username
    #password: your_password

counter:
    counter:
        name: counter_consumption
        initial: 0
        step: 1

device_tracker:
  - platform: owntracks
    max_gps_accuracy: 30  
    waypoints: True
    waypoint_whitelist:
    - !secret tracker_person_1
    - !secret tracker_person_2
    - !secret tracker_person_3
    - !secret tracker_person_4


# Weather prediction
sensor:
  - platform: yr

#  - platform: darksky
#    api_key: 39ac59c184a5a9ac992a1f6bcfbe0702
#    name : "Pogoda"
#    update_interval :
#      minutes : 3
#    latitude : 52.37885
#    longitude : 20.91745
#    monitored_conditions:
#      - icon
#      - temperature
#      - apparent_temperature
#      - dew_point
#      - wind_speed
#      - wind_bearing
#      - humidity
#      - pressure

  - platform: systemmonitor
    resources:
      - type: disk_use_percent
        arg: /home
      - type: memory_free
      - type: load_1m
      - type: load_5m
      - type: load_15m
      - type: processor_use
      - type: last_boot


  - ESP-sypialnia-akwarium:
    platform: mqtt
    name: "Sypialnia/akwarium"
    state_topic: "light/5b2a1900/temperature"
    qos: 0
    unit_of_measurement: "ºC"

#  - platform: onewire
#    names:
#      02.AF2E7B140000: "cos"
#      28.0F395F030000: "Dzieciecy"
#      28.41765F030000: "Podwórze"
#      28.9F915F030000: "Hydrofor"
#      28.A93C5F030000: "D-Z"
#      28.AF715F030000: "D-P"
#      28.C5625F030000: "G-P"
#      28.EA905F030000: "G-Z"
#      28.EB615F030000: "Podłoga"
#    mount_dir: /mnt/1wire

  - platform: mqtt
    state_topic: "heating/stove/temp/28ecd97d6003"
    name: "defro"
    unit_of_measurement: "ºC"

  - platform: mqtt
    state_topic: "temperature/home/babyroom"
    name: "babyroom"
    unit_of_measurement: "ºC"

  - platform: mqtt
    state_topic: "temperature/outdoor/outside"
    name: "outside"
    unit_of_measurement: "ºC"

            ############ statistic sensor ############
  - platform: history_stats
    name: carbon_consumption_1d
    entity_id: binary_sensor.carbon_consumption
    state: 'on'
    type: count 
    #    start: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
    end: '{{ now() }}'
    duration:
      hours: 24

  - platform: history_stats
    name: carbon_consumption_1month
    entity_id: binary_sensor.carbon_consumption
    state: 'on'
    type: count 
    start: '{{ now().replace(day=1).replace(hour=0).replace(minute=0).replace(second=0) }}'
    end: '{{ now() }}'


#  - platform: history_stats
#    name: test_consumption_1d
#    entity_id: binary_sensor.test
#    state: 'on'
#    type: count
#    start: '{{ now().replace(hour=14).replace(minute=0).replace(second=0) }}'
#    end: '{{ now() }}'

#  - platform: template
#    sensors:
#      test_consumption_1d:
#        friendly_name: 'test opał'
#        unit_of_measurement: 'kg'
#        #value_template: '{{ states.sensor.test_consumption_1d.state|float * 3 }}'
#        value_template: '{{ states("sensor.test_consumption_1d.state") }}'


binary_sensor:
  - platform: mqtt
    state_topic: "heating/controller"
    name: "heating_stove"
    payload_on: "ON"
    payload_off: "OFF"

  - platform: mqtt
    state_topic: "heating/stove/consumption"
    name: carbon_consumption
    payload_on: 1
    payload_off: 0
  
  - platform: mqtt
    state_topic: "test/test"
    name: test
    payload_on: 1
    payload_off: 0

switch:
  - platform: mqtt
    name: "Bedroom Switch"
    state_topic: "home/bedroom/switch1"
    command_topic: "home/bedroom/switch1/set"
    availability_topic: "home/bedroom/switch1/available"
    payload_on: "ON"
    payload_off: "OFF"
    optimistic: false
    qos: 0
    retain: true

  - platform: mqtt
    name: "MQTT Switch 3"
    state_topic: "house/switch3/"
    command_topic: "house/switch3/set"
    payload_on: "ON"
    payload_off: "OFF"
    qos: 0
    retain: true   

light:
  - platform: mqtt
    name: "aqua_light"
    #state_topic: "second_floor/aquarium/state"
    command_topic: "second_floor/aquarium/cmd"
    qos: 0
    payload_on: "relay1:ON"
    payload_off: "relay1:OFF"
    optimistic: false

  - platform: mqtt
    name: "aqua_pump"
    #state_topic: "second_floor/aquarium/state"
    command_topic: "second_floor/aquarium/cmd"
    qos: 0
    payload_on: "relay2:ON"
    payload_off: "relay2:OFF"
    optimistic: false

# Text to speech
tts:
  - platform: google


google:
    client_id: !secret google_client_id 
    client_secret: !secret google_client_secret

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml

